version: '3.8'

services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_RAG_WEB_SEARCH=True'
      - 'RAG_WEB_SEARCH_ENGINE=searxng'
      - 'RAG_WEB_SEARCH_RESULT_COUNT=3'
      - 'RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10'
      - 'SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>'
      - 'OPENAI_API_BASE_URL=http://host.docker.internal:9099'
      - 'OPENAI_API_KEY=0p3n-w3bu!'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - open-webui
    volumes:
      - /home/atgehrhardt/openwebui/nginx/self-signed:/etc/ssl/self-signed
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped

volumes:
  open-webui: {}